# Generated by Django 4.2.7 on 2025-04-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
