# Generated by Django 4.2.7 on 2025-04-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidateprofile_about_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='education_level',
        ),
    ]
